### ISSUE TITLE
[FLINK-11219] Upgrade Jackson version to 2.9.6

### ISSUE THREAD

**Issue by XuQianJin-Stars** [apache/flink-shaded#53]
1. Upgrade Jackson version to 2.9.6
Because the Jackson version supported by calcite1.18.0 has been upgraded to Jackson 2.9.6.
2. Need to upgrade flink jackson in the shaded version
Because many flink dependency from the flink-shaded.

**Comment by zentol** [comment]
It doesn't make sense to bump jackson to share it with calcite.

This _could_ only work if you can safely relocate jackson usages in calcite in the first place, but that means we don't have to share flink-shaded-jackson. We can just let calcite use it's own own (relocated) version.
You'd just end up with unnecessary coupling between Flink and Calcite along with a more brittle build process (since the shading pattern in flink-table has to match flink-shaded-jackson).

**Comment by zentol** [comment]
We no longer maintain issues on github.
